% ---------------------------------------------------------------------- %
%
% Double Wishbone Suspension Simulator - printSimulationParams.m
% Fuction to add the simulation parameters to the plot
% 
%
% Notes:
%
%   - 
%
% ---------------------------------------------------------------------- %

function printSimulationParams(params) 

    % Add parameters
    dim = [.15 .6 0.3 0.3];
    params = { 'Simulation Parameters:',...
               sprintf('R-UCA x: %d', params(1)),... 
               sprintf('R-UCA y: %d', params(2)),... 
               sprintf('R-LCA x: %d', params(3)),... 
               sprintf('R-LCA y: %d', params(4)),... 
               sprintf('UCA length: %d', params(5)),... 
               sprintf('LCA length: %d', params(6)),... 
               sprintf('Upright length: %d', params(7)),... 
               sprintf('Spindle height: %d', params(8)),... 
               sprintf('Wheel offset: %d', params(9)),... 
               sprintf('Wheel diameter: %d', params(10)),... 
               sprintf('Spindle angle: %d', params(11)) };
    annotation('textbox',dim,'String',params,'FitBoxToText','on');
    
end